name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True

      - name: Install dependencies (Linux)
        if: startsWith(runner.os, 'Linux')
        run: sudo apt-get -y install libtbb-dev r-base-dev r-base electric-fence r-mathlib

      - name: Install dependencies (macOS)
        if: startsWith(runner.os, 'macOS')
        run: brew install tbb r electric-fence

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify pytest

      - name: Build
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ pylira_simd

      - name: Test
        run: pytest tests
