name: "Pip"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build with Pip
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest]
        python-version: ["3.9"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: True
    
    - uses: actions/cache@v2
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v2
      if: startsWith(runner.os, 'macOS')
      with:
        path: ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies (Linux)
      if: startsWith(runner.os, 'Linux')
      run: sudo apt-get -y install libtbb-dev r-base-dev r-base electric-fence r-mathlib

    - name: Install dependencies (macOS)
      if: startsWith(runner.os, 'macOS')
      run: brew install libtbb-dev r-base-dev r-base electric-fence r-mathlib

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: pytest
